spring:
  application:
    name: circuit-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key:
      chat:
        options:
          model: qwen-plus
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json




server:
  port: 8124
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.eric.circuitagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai: DEBUG


search-api:
  api-key:
